version: '3'

services:

  php:
    build:
      context: ./docker/php
      args:
        COMPOSER_HASH: "${COMPOSER_HASH}"
    container_name: "${CONTAINER_NAME_PREFIX}_php"
    volumes:
      - .:/var/www/html:cached

  mariadb:
    image: mariadb
    restart: always
    container_name: "${CONTAINER_NAME_PREFIX}_mariadb"
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
